# Generated by Django 4.2.4 on 2023-08-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1991-11-11'),
            preserve_default=False,
        ),
    ]
